export const ActionTypes = {
    LOGIN_STATUS: "LOGIN_STATUS",
    ADMIN_STATUS: "ADMIN_STATUS",
    CATEGORY_DATA: "CATEGORY_DATA",
    PRODUCT_DATA: "PRODUCT_DATA",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    LOGOUT: "LOGOUT",
    USER_DETAIL: "USER_DETAIL",
    CARTS_DETAIL: "CARTS_DETAILS",
    CART_ID: "CART_ID",
    WISHLIST_INFO: "WISHLIST_INFO"
}