export const ActionTypes = {
    LOGIN_STATUS: "LOGIN_STATUS",
    ADMIN_STATUS: "ADMIN_STATUS",
    CATEGORY_DATA: "CATEGORY_DATA",
    PRODUCT_DATA: "PRODUCT_DATA",
    PRODUCT_REMOVE_DATA: "PRODUCT_REMOVE_DATA"
}